// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperDuperRescueHeads.Infrastructure.Data;

#nullable disable

namespace SuperDuperRescueHeads.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202040740_AddCollections")]
    partial class AddCollections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Collections.Collection", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CollectionId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Collections_IsDeleted")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Collections_OwnerId");

                    b.HasIndex("OwnerId", "IsDeleted")
                        .HasDatabaseName("IX_Collections_OwnerId_IsDeleted")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Groups.GroupMember", b =>
                {
                    b.Property<Guid>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupMemberId");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserGroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMembers", (string)null);
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Groups.GroupSyncEvent", b =>
                {
                    b.Property<Guid>("GroupSyncEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MembersAdded")
                        .HasColumnType("int");

                    b.Property<int>("MembersRemoved")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SyncCompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SyncStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupSyncEventId");

                    b.HasIndex("Status");

                    b.HasIndex("UserGroupId", "SyncStartedAt");

                    b.ToTable("GroupSyncEvents", (string)null);
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Groups.UserGroup", b =>
                {
                    b.Property<Guid>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserGroupId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GroupName");

                    b.ToTable("UserGroups", (string)null);
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Items.ConflictEvent", b =>
                {
                    b.Property<Guid>("ConflictEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConflictDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ConflictResolutionMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LosingUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("NotificationSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("VersionAtConflict")
                        .HasMaxLength(8)
                        .HasColumnType("varbinary(8)");

                    b.Property<Guid>("WinningUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConflictEventId");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_ConflictEvents_ItemId");

                    b.HasIndex("LosingUserId")
                        .HasDatabaseName("IX_ConflictEvents_LosingUserId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_ConflictEvents_OccurredAt");

                    b.HasIndex("WinningUserId")
                        .HasDatabaseName("IX_ConflictEvents_WinningUserId");

                    b.ToTable("ConflictEvents", (string)null);
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Items.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcquisitionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ItemId");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("IX_Items_CollectionId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Items_CreatedAt");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Items_DeletedAt")
                        .HasFilter("[IsDeleted] = 1");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NavigationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TriggeredByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Sharing.CollectionShare", b =>
                {
                    b.Property<Guid>("CollectionShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<Guid>("SharedWithUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CollectionShareId");

                    b.HasIndex("GroupId")
                        .HasFilter("[GroupId] IS NOT NULL");

                    b.HasIndex("InvitationToken")
                        .IsUnique();

                    b.HasIndex("CollectionId", "GroupId")
                        .HasFilter("[GroupId] IS NOT NULL");

                    b.HasIndex("CollectionId", "SharedWithUserId")
                        .IsUnique()
                        .HasFilter("[Status] = 1");

                    b.HasIndex("CollectionId", "Status");

                    b.HasIndex("SharedWithUserId", "Status");

                    b.ToTable("CollectionShares", (string)null);
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Infrastructure.Data.Entities.UserSearchHistory", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SearchTerm")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("SearchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("UserId", "SearchTerm");

                    b.HasIndex("UserId", "SearchedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_UserSearchHistory_SearchedAt");

                    b.ToTable("UserSearchHistory", (string)null);
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Groups.GroupMember", b =>
                {
                    b.HasOne("SuperDuperRescueHeads.Domain.Groups.UserGroup", null)
                        .WithMany("_members")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Items.Item", b =>
                {
                    b.HasOne("SuperDuperRescueHeads.Domain.Collections.Collection", null)
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SuperDuperRescueHeads.Domain.Items.ItemName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Name");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Collections.Collection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SuperDuperRescueHeads.Domain.Groups.UserGroup", b =>
                {
                    b.Navigation("_members");
                });
#pragma warning restore 612, 618
        }
    }
}
